iio: hmc425a: enforce that 6 GPIOs are defined
There build warnings/errors in the newer kernel is:
```
drivers/iio/amplifiers/hmc425a.c:50:2: error: ISO C90 forbids variable length array 'values' [-Werror=vla]
   50 |  int i, values[st->gpios->ndescs];
      |  ^~~
```

Seems that it does not allow C99 variable-length-arrays.

This change also enforces that a fixed number 6 GPIOs are defined, and
returns -ENODEV if the number of GPIOs isn't exactly 6.

The HMC425A needs to be controlled via GPIOs, and the driver should make
sure that the number is exactly as-needed [no-more no-less] so that the
GPIOs are not left to dangle.

Signed-off-by: Alexandru Ardelean <alexandru.ardelean@analog.com>
(cherry picked from commit 7e8f973febffa2e0939fca475e00258846280318)